(part "0415002_DRSP"
    (packageRef "0415063DRSP")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Manufacturer_Name" "LITTELFUSE")
    (property "Manufacturer_Part_Number" "0415002.DRSP")
    (property "Description" "NANO2 > 277 V > 15mm x 5mm Sq. > Time Lag")
    (property "Datasheet_Link" "https://www.littelfuse.com/assetdocs/littelfuse-fuse-nano-415sp-datasheet-final?assetguid=b78402d8-903c-4579-afe2-2d0239b305c4")
    (property "symbolName1" "0415002_DRSP")
)
