(part "CDBQR42"
    (packageRef "CDBQR42")
    (interface
        (port "1" (symbPinId 1) (portName "K") (portType INOUT))
        (port "2" (symbPinId 2) (portName "A") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "750-CDBQR42")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Comchip-Technology/CDBQR42?qs=tw%252BuQ%2FB6PO2J71PLqQTLpQ%3D%3D")
    (property "Manufacturer_Name" "Comchip Technology")
    (property "Manufacturer_Part_Number" "CDBQR42")
    (property "Description" "Schottky Diodes & Rectifiers 200mA 30V DFN Sm. Sgnl. Schottky")
    (property "Datasheet_Link" "https://www.comchiptech.com/admin/files/product/QW-G1101-CDBQR42-43-HF-RevA411201.pdf")
    (property "symbolName1" "CDBQR42")
)
