(part "RB058L-30DDTE25"
    (packageRef "DIOM5026X220N")
    (interface
        (port "1" (symbPinId 1) (portName "K") (portType INOUT))
        (port "2" (symbPinId 2) (portName "A") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "122")
    (property "Mouser_Part_Number" "755-RB058L-30DDTE25")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/ROHM-Semiconductor/RB058L-30DDTE25?qs=4v%252BiZTmLVHH4qQzteWzq7g%3D%3D")
    (property "Manufacturer_Name" "ROHM Semiconductor")
    (property "Manufacturer_Part_Number" "RB058L-30DDTE25")
    (property "Description" "Features Inner Circuit High reliability Small power mold type Super low IR")
    (property "Datasheet_Link" "")
    (property "symbolName1" "RB058L-30DDTE25")
)
